spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

    hibernate:
      ddl-auto: validate

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem