spring:
  datasource:
    url: jdbc:mariadb://database:3306/example?useSSL=false
    username: root
    password: example

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always